spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #          uri: https://github.com/sureshstalin/config-repo.git
          uri: file:///D:\Suresh\workspace-billingsystem\billing-cloud-services\config-repo
          default-label: main
server:
  port: 8888
#eureka:
#  instance:
#    hostname: 65.0.46.26
#  client:
#    serviceUrl:
#      defaultZone: http://65.1.222.21:8761/eureka/

#spring.cloud.config.server.git.uri=https://github.com/sureshstalin/config-files.git
#spring.cloud.config.server.git.username=suresh_stalin
#spring.cloud.config.server.git.password=kesavan123$$
#spring.cloud.config.server.git.uri=file:///C:/Users/ssure/test-files

#spring.cloud.config.server.git.username=ssuresh.saikishore@gmail.com
#spring.cloud.config.server.git.password=kesavan123$$
#spring.cloud.config.server.bootstrap=true
