server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/billingdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: suresh
    password: suresh123$$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update