spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///D:\ms-cloud-demo\ms-config-repo
#          uri: https://github.com/sureshstalin/config-repo.git
#          default-label: main
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka